stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - pip install -r requirements.txt
    - python setup.py sdist bdist_wheel

test_job:
  stage: test
  script:
    - pip install pytest
    - pytest

deploy_job:
  stage: deploy
  script:
    - docker build -t my-image .
    - docker push my-registry/my-image
